INSERT INTO LEGO_PIECES(NAME, CATEGORY, PRICE) VALUES('Mindstorms v3', 'MINDSTORMS', 342.12);
INSERT INTO LEGO_PIECES(NAME, CATEGORY, PRICE) VALUES('Firefighters', 'CITY', 42.12);
INSERT INTO LEGO_PIECES(NAME, CATEGORY, PRICE) VALUES('Camp Nou', 'CITY', 312.12);
INSERT INTO LEGO_PIECES(NAME, CATEGORY, PRICE) VALUES('Train', 'CITY', 142.12);
INSERT INTO LEGO_PIECES(NAME, CATEGORY, PRICE) VALUES('PEPPA PIG', 'DUPLO', 22.12);