CREATE TABLE LEGO_PIECES
(
    ID       INT GENERATED ALWAYS AS IDENTITY,
    NAME     VARCHAR(30)   NOT NULL,
    CATEGORY VARCHAR(20)   NOT NULL,
    PRICE    DECIMAL(5, 2) NOT NULL,
    PRIMARY KEY (ID)
);